// Entry point that wires this project's recompiled game code up to
// N64ModernRuntime (ultramodern + librecomp) and RecompFrontend
// (recompui + recompinput): graphics/window, audio, input and config
// callbacks. Game-specific behaviour lives in src/game/.
//
// Launcher/UI assets: the Exo 2 UI font, Noto Emoji and PromptFont (which
// RecompFrontend loads itself), each with its license in assets/, and our
// own icons (tools/make_icons.py).
//
// Not done yet: no mod/texture-pack content types and no launcher menu
// customization (the library's default_launcher_init_callback runs; on
// Android src/android/android_launcher.cpp adds Change ROM to it).

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cinttypes>
#include <mutex>
#include <vector>
#include <filesystem>
#include <exception>
#include <string>

#include "nfd.h"

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"

#define SDL_MAIN_HANDLED
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include "SDL.h"
#include "SDL_syswm.h"
#else
#include "SDL2/SDL.h"
#endif

#include "btga_android.h"
#include "recompui/recompui.h"
#include "recompui/program_config.h"
#include "recompui/renderer.h"
#include "recompui/config.h"
#include "util/file.h"

#include "recompinput/input_state.h"
#include "recompinput/input_events.h"
#include "recompinput/profiles.h"
#include "recompinput/players.h"

#include "librecomp/game.hpp"
#include "librecomp/helpers.hpp"

#include "btga_config.h"

#if defined(BTGA_HAS_APP_ICON)
#include "icon_bytes.h"
#include "stb/stb_image.h"
#endif

// Generated into RecompiledFuncs/funcs.h by N64Recomp from this project's
// own battletanxga.us.rev0.toml (renamed from func_80071000 -- see
// [input] entrypoint in that file).
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// register_overlays.cpp -- wires N64Recomp's generated function-address
// lookup table into librecomp's runtime overlay system. Without this,
// indirect calls (function pointers/jump tables) fail with "Failed to find
// function at 0x..." -- see that file's own comment for the full story.
void register_btga_overlays();

namespace btga {
    void apply_theme(); // theme.cpp
}

static const std::string program_name = "BattleTanx: Global Assault Recompiled";
static const std::u8string program_id = u8"btgarecomp";
static const std::string version_string = "0.1.0";

template <typename... Ts>
[[noreturn]] static void exit_error(const char* fmt, Ts... args) {
    char buf[1024];
    std::snprintf(buf, sizeof(buf), fmt, args...);
    fprintf(stderr, "%s\n", buf);
    ultramodern::error_handling::message_box(buf);
    ultramodern::error_handling::quick_exit(__FILE__, __LINE__, __FUNCTION__);
}

// --- RSP microcode dispatch -------------------------------------------
// Returning nullptr is the documented "not implemented" signal
// (recomp::rsp::callbacks_t::get_rsp_microcode_t's doc comment) --
// ultramodern prints the task type to stderr and exits rather than running
// with garbage microcode.
#ifdef BTGA_HAS_RSP_AUDIO
// rsp/n_aspMain.cpp, generated by RSPRecomp from n_aspMain.us.rev0.toml
// (STATUS.md round 90). Graphics tasks are handled by RT64's own HLE.
RspExitReason n_aspMain(uint8_t* rdram, uint32_t ucode_addr);
#endif

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
#ifdef BTGA_HAS_RSP_AUDIO
    case M_AUDTASK:
        return n_aspMain;
#endif
    default:
        fprintf(stderr, "No RSP microcode registered for task type %" PRIu32 ".\n", task->t.type);
        return nullptr;
    }
}

// --- Graphics / windowing -----------------------------------------------

// recompui's own code (ui_state.cpp) declares this as `extern SDL_Window*
// window;` and reads it directly -- not `static`, needs external linkage.
SDL_Window* window = nullptr;

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {

    SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, "1");
    SDL_SetHint(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, "1");

    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC) != 0) {
        exit_error("Failed to initialize SDL2: %s", SDL_GetError());
    }

    return {};
}

// The window/taskbar icon, from icons/app.png (embedded as icon_bytes, decoded
// with the stb_image that RT64 already links in). The .exe's own icon comes
// from icons/app.rc on Windows.
static void set_window_icon(SDL_Window* window) {
#if defined(BTGA_HAS_APP_ICON)
    int width, height, channels;
    stbi_uc* pixels = stbi_load_from_memory(reinterpret_cast<const stbi_uc*>(icon_bytes), (int)icon_bytes_size, &width, &height, &channels, 4);
    if (pixels == nullptr) {
        return;
    }
    SDL_Surface* surface = SDL_CreateRGBSurfaceWithFormatFrom(pixels, width, height, 32, width * 4, SDL_PIXELFORMAT_RGBA32);
    if (surface != nullptr) {
        SDL_SetWindowIcon(window, surface);
        SDL_FreeSurface(surface);
    }
    stbi_image_free(pixels);
#else
    (void)window;
#endif
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {

    uint32_t flags = SDL_WINDOW_RESIZABLE;
#if defined(__APPLE__)
    flags |= SDL_WINDOW_METAL;
#elif defined(RT64_SDL_WINDOW_VULKAN) || defined(__ANDROID__)
    // RT64_SDL_WINDOW_VULKAN is only defined on Linux (see CMakeLists.txt) --
    // Windows uses plume's D3D12 backend instead, which doesn't need an SDL
    // window flag (it talks to the GPU through the raw HWND returned below).
    // On Android the flag matters too: without a graphics flag SDL defaults
    // to OpenGL there and connects an EGL surface to the window, after which
    // Vulkan can't create its own surface on it.
    flags |= SDL_WINDOW_VULKAN;
#endif
#if defined(__ANDROID__)
    // Always fullscreen on Android: SDL then hides the system bars (immersive mode), so the game
    // gets the whole screen (16:9 on the Retroid Pocket 6, not 1920x914) like the desktop
    // builds' fullscreen. The window mode setting goes through RT64, which has no Android path.
    flags |= SDL_WINDOW_FULLSCREEN_DESKTOP;
#endif

    window = SDL_CreateWindow(program_name.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1280, 720, flags);
    if (window == nullptr) {
        exit_error("Failed to create window: %s", SDL_GetError());
    }
    set_window_icon(window);

#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    if (!SDL_GetWindowWMInfo(window, &wm_info)) {
        exit_error("Failed to get window info: %s", SDL_GetError());
    }
    return ultramodern::renderer::WindowHandle{ wm_info.info.win.window, GetCurrentThreadId() };
#elif defined(__linux__) || defined(__ANDROID__)
    return ultramodern::renderer::WindowHandle{ window };
#else
    static_assert(false && "Only Linux and Windows are set up in this file so far.");
#endif
}

static void update_gfx(void*) {
    // poll_inputs() only reads already-buffered SDL state (SDL_GetKeyboardState,
    // etc.) -- it never calls SDL_PollEvent, so it never pumps the window's
    // message queue. That's handle_events()'s job (see recompinput's
    // input_events.cpp): without calling it here, the window's message loop
    // is never serviced, and Windows marks it "Not Responding" even though
    // nothing has actually crashed or deadlocked. poll_inputs() is already
    // correctly wired as the ultramodern input_callbacks_t::poll_input
    // callback and doesn't need to run again from here too.
    recompinput::handle_events();

    // Mirrors RT64's Expand target (rt64_workload_queue.cpp): the window's
    // aspect ratio, never narrower than the game's 4:3.
    float widescreen_scale = 1.0f;
    if (ultramodern::renderer::get_graphics_config().ar_option == ultramodern::renderer::AspectRatio::Expand) {
        int width = 0, height = 0;
        SDL_GetWindowSize(window, &width, &height);
        if (width > 0 && height > 0) {
            widescreen_scale = std::max(1.0f, (float(width) / float(height)) / (4.0f / 3.0f));
        }
    }
    btga::set_widescreen_scale(widescreen_scale);
}

// --- Audio ----------------------------------------------------------------
// Push-based playback: queue whatever the game hands us, report how much is
// still queued. SDL converts from the game's sample rate to the device's.

static SDL_AudioDeviceID audio_device = 0;
static std::mutex audio_mutex;
static constexpr uint32_t audio_channels = 2;
static uint32_t game_frequency = 44100;

// Extra audio the game is told it still needs to generate, beyond what's
// actually queued. The game sizes each audio task from osAiGetLength, so
// without this margin a late audio thread wakeup (they're host threads here,
// not hardware interrupts) lets the queue run dry for a moment: crackle.
static constexpr uint32_t audio_headroom_vis = 2;

// Latency cap. Nothing drains a surplus on its own: when the game delivers a
// burst faster than real time (e.g. skipping a cutscene), the extra stays
// queued and every sound after it plays late by that much. Above the soft
// cap incoming chunks are dropped until it's back under (a small surplus
// drains without a gap); above the hard cap the queue is cleared at once.
static constexpr uint32_t audio_soft_cap_ms = 200;
static constexpr uint32_t audio_hard_cap_ms = 500;

static bool open_audio_device(uint32_t frequency) {
    std::lock_guard<std::mutex> lock(audio_mutex);

    if (audio_device != 0) {
        SDL_CloseAudioDevice(audio_device);
        audio_device = 0;
    }

    SDL_AudioSpec desired{};
    desired.freq = static_cast<int>(frequency);
    desired.format = AUDIO_F32SYS;
    desired.channels = static_cast<Uint8>(audio_channels);
    desired.samples = 512;

    // No allowed changes: SDL resamples to whatever the device runs at, so
    // queued audio is always in the game's own rate.
    audio_device = SDL_OpenAudioDevice(nullptr, 0, &desired, nullptr, 0);
    game_frequency = frequency;
    if (audio_device == 0) {
        fprintf(stderr, "Failed to open audio device: %s (continuing without sound)\n", SDL_GetError());
        return false;
    }

    SDL_PauseAudioDevice(audio_device, 0);
    return true;
}

static void queue_samples(int16_t* audio_data, size_t sample_count) {
    if (audio_device == 0) {
        return;
    }

    // Each stereo frame is one 32-bit word in RDRAM, which is stored
    // word-swapped, so the two 16-bit halves read back right-then-left.
    static std::vector<float> buffer;
    buffer.resize(sample_count);
    float scale = static_cast<float>(recompui::config::sound::get_main_volume() / 100.0) / 32768.0f;
    for (size_t i = 0; i + 1 < sample_count; i += 2) {
        buffer[i + 0] = audio_data[i + 1] * scale;
        buffer[i + 1] = audio_data[i + 0] * scale;
    }

    std::lock_guard<std::mutex> lock(audio_mutex);
    // Testing switch: BTGA_NO_AUDIO_CAP=1 queues everything, as before round 124.
    static const bool no_audio_cap = [] { const char* v = std::getenv("BTGA_NO_AUDIO_CAP"); return v != nullptr && v[0] != '\0' && v[0] != '0'; }();
    if (no_audio_cap) {
        SDL_QueueAudio(audio_device, buffer.data(), static_cast<Uint32>(sample_count * sizeof(float)));
        return;
    }
    const size_t bytes_per_ms = game_frequency * audio_channels * sizeof(float) / 1000;
    const size_t queued_bytes = SDL_GetQueuedAudioSize(audio_device);
    if (queued_bytes > audio_hard_cap_ms * bytes_per_ms) {
        printf("[BTGA AUDIO] %zu ms queued, resyncing\n", queued_bytes / bytes_per_ms);
        fflush(stdout);
        SDL_ClearQueuedAudio(audio_device);
    }
    else if (queued_bytes > audio_soft_cap_ms * bytes_per_ms) {
        return;
    }
    SDL_QueueAudio(audio_device, buffer.data(), static_cast<Uint32>(sample_count * sizeof(float)));
}

static size_t get_frames_remaining() {
    if (audio_device == 0) {
        return 0;
    }
    std::lock_guard<std::mutex> lock(audio_mutex);
    size_t queued_frames = SDL_GetQueuedAudioSize(audio_device) / (audio_channels * sizeof(float));
    size_t headroom_frames = game_frequency / 60 * audio_headroom_vis;
    return queued_frames > headroom_frames ? queued_frames - headroom_frames : 0;
}

static void set_frequency(uint32_t frequency) {
    if (frequency != game_frequency) {
        open_audio_device(frequency);
    }
}

// --- Input ------------------------------------------------------------

// Port 1 is always plugged in. In local multiplayer, so is one port per
// assigned player; in single-player mode every controller drives player 1,
// so the other ports must stay empty or they'd mirror player 1's input.
//
// The runtime's Pak enum has no Controller Pak, so any pak is reported as a
// Rumble Pak here; that only sets "something is plugged in" in the status
// the game queries. What it finds when it probes is decided per port by
// src/game/controller_pak_hle.cpp's osPfsInitPak.
static ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    size_t ports = 1;
    if (!recompinput::players::is_single_player_mode()) {
        ports = std::max<size_t>(1, recompinput::players::get_number_of_assigned_players());
    }
    if (controller_num < 0 || (size_t)controller_num >= ports) {
        return ultramodern::input::connected_device_info_t{
            .connected_device = ultramodern::input::Device::None,
            .connected_pak = ultramodern::input::Pak::None,
        };
    }
    bool has_pak = btga::config::get_accessory(controller_num) != btga::config::Accessory::None;
    return ultramodern::input::connected_device_info_t{
        .connected_device = ultramodern::input::Device::Controller,
        .connected_pak = has_pak ? ultramodern::input::Pak::RumblePak : ultramodern::input::Pak::None,
    };
}

#if defined(__ANDROID__)
// Player 1 also gets the on-screen touch controls, unless one of the game's menus has the input.
static bool get_n64_input_with_touch(int player_index, uint16_t* buttons_out, float* x_out, float* y_out) {
    const bool got = recompinput::profiles::get_n64_input(player_index, buttons_out, x_out, y_out);
    if ((player_index == 0) && !recompinput::game_input_disabled()) {
        btga::android::add_touch_input(buttons_out, x_out, y_out);
    }
    return got;
}
#endif

// --- Misc callbacks -----------------------------------------------------

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// --- Game registration --------------------------------------------------
// recompui's own default launcher menu (ui_launcher.cpp) reads this exact
// global by name -- it must exist with this type for the link to succeed.
std::vector<recomp::GameEntry> supported_games = {
    {
        // XXH3_64 of the normalized big-endian .z64 (tools/normalize_rom.py),
        // computed against the ROM this project has been developed against
        // (see syms/rom_info.md) -- NOT the N64 header CRC1/CRC2.
        .rom_hash = 0x9c7467e763553529ULL,
        .internal_name = "BattleTanxGA",
        .display_name = "BattleTanx: Global Assault",
        .game_id = u8"btga.n64.us.1.0",
        .mod_game_id = "btga",
        // The game saves only to a Controller Pak
        // (src/game/controller_pak_hle.cpp); the cartridge has no save chip.
        // AllowAll is kept so the runtime still answers any probe sensibly.
        .save_type = recomp::SaveType::AllowAll,
        .thumbnail_bytes = {},
        .is_enabled = true,
        .decompression_routine = nullptr,
        .has_compressed_code = false,
        // entrypoint_address is a gpr (uint64_t). A plain 0x80071000 literal
        // zero-extends to 0x0000000080071000 -- but the MEM_B/MEM_W/MEM_H
        // macros (N64Recomp/include/recomp.h) subtract the *sign-extended*
        // KSEG0 base (0xFFFFFFFF80000000, matching real MIPS64 register
        // semantics: a 32-bit value in a 64-bit register is always sign-
        // extended), so a zero-extended address computes a ~4GB-off offset
        // into rdram instead of the intended small one, segfaulting on the
        // very first RDRAM write in do_rom_read(). Cast through int32_t
        // first to sign-extend, matching what N64Recomp's own generated
        // get_entrypoint_address() (RecompiledFuncs/lookup.cpp) does for
        // exactly this reason.
        .entrypoint_address = (gpr)(int32_t)0x80071000u,
        .entrypoint = recomp_entrypoint,
        .on_init_callback = nullptr,
    },
};

// std::terminate (any uncaught C++ exception, on any thread -- recomp::start
// spawns several) leads straight into ucrtbase's fail-fast abort path, which
// tears the process down without running atexit handlers or flushing stdio
// buffers. That's why redirected runs (`... > run_output.txt 2>&1`) have
// been showing up empty even when something threw and printed nothing --
// this handler force-flushes and prints the exception's own message first
// so it actually survives redirection.
// The message also goes to crash_log.txt (src/main/crash_handler.cpp), since
// release builds have no console.
void btga_report_fatal_error(const char* message);

[[noreturn]] static void report_unhandled_exception_and_abort() {
    std::string message = "std::terminate() called with no active exception";
    if (std::exception_ptr eptr = std::current_exception()) {
        try {
            std::rethrow_exception(eptr);
        } catch (const std::exception& e) {
            message = std::string("uncaught C++ exception: ") + e.what();
        } catch (...) {
            message = "uncaught C++ exception of an unrecognized type";
        }
    }
    fflush(stdout);
    btga_report_fatal_error(message.c_str());
    std::abort();
}

int main(int argc, char** argv) {
#if defined(__ANDROID__)
    btga::android::startup();
#endif
    std::set_terminate(report_unhandled_exception_and_abort);

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        fprintf(stderr, "Invalid version string: %s\n", version_string.c_str());
        return EXIT_FAILURE;
    }

    register_btga_overlays();
    btga::apply_theme();

    NFD_Init();

    recompui::programconfig::set_program_name(program_name);
    recompui::programconfig::set_program_id(program_id);

    SDL_InitSubSystem(SDL_INIT_AUDIO);
    if (!open_audio_device(game_frequency)) {
        fprintf(stderr, "Continuing without sound.\n");
    }

    // Exo 2 (SIL OFL 1.1, assets/EXO2_LICENSE.txt), a variable font covering
    // every weight the UI uses. The family name must match the one stored
    // inside the font file: recompui's generated base stylesheet sets
    // `font-family` to it, and RmlUi draws no text for a family it never
    // loaded (STATUS.md round 86).
    recompui::register_primary_font("Exo2.ttf", "Exo 2");

    recomp::register_config_path(recompui::file::get_app_folder_path());

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

#if defined(__ANDROID__)
    btga::android::import_picked_rom(supported_games[0].game_id);
#endif

    recompinput::players::set_single_player_mode(true);

    // recompui::config::init_modal() (called from UIState::create_menus(),
    // itself called from inside RT64::Application::setup() on the gfx
    // thread) hard-requires recompui::config::finalize() to have already
    // run -- without it, "loaded_configs" stays false and/or the config
    // system is left in a state RT64/recompui doesn't expect, which was
    // crashing startup entirely (see STATUS.md). So the config tabs are
    // created and finalized here, before recomp::start().
    recompui::config::GeneralTabOptions general_tab_options{};
    btga::config::add_general_options(recompui::config::create_general_tab(general_tab_options));
    recompui::config::create_graphics_tab();
    recompui::config::create_controls_tab();
    recompui::config::create_sound_tab();
    recompui::config::create_mods_tab();
    recompui::config::finalize();

    // Read from the just-loaded config; takes effect on the next launch if
    // changed in the menu.
    if (btga::config::get_local_multiplayer()) {
        recompinput::players::set_single_player_mode(false);
    }

    recomp::rsp::callbacks_t rsp_callbacks{
        .get_rsp_microcode = get_rsp_microcode,
    };

    ultramodern::renderer::callbacks_t renderer_callbacks{
        .create_render_context = [](uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
            auto presentation_mode = ultramodern::renderer::PresentationMode::PresentEarly;
            return recompui::renderer::create_render_context(rdram, window_handle, presentation_mode, developer_mode);
        },
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = create_gfx,
        .create_window = create_window,
        .update_gfx = update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks{
        .queue_samples = queue_samples,
        .get_frames_remaining = get_frames_remaining,
        .set_frequency = set_frequency,
    };

    ultramodern::input::callbacks_t input_callbacks{
        .poll_input = recompinput::poll_inputs,
#if defined(__ANDROID__)
        .get_input = get_n64_input_with_touch,
#else
        .get_input = recompinput::profiles::get_n64_input,
#endif
        .set_rumble = recompinput::set_rumble,
        .get_connected_device_info = get_connected_device_info,
    };

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = recompinput::update_rumble,
        .gfx_init_callback = nullptr,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = recompui::message_box,
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = get_game_thread_name,
    };

    // recompui's own default launcher menu is used (see file-level comment);
    // on Android the same one plus Change ROM.
#if defined(__ANDROID__)
    btga::android::register_launcher();
#endif

    recomp::start({
        .argc = argc,
        .argv = argv,
        .project_version = project_version,
        .window_handle = {}, // created by gfx_callbacks.create_window
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
        .message_queue_control = {}, // the runtime's defaults
    });

    NFD_Quit();

    // The game's threads are never joined by the runtime and may still be
    // blocked on (or spinning over) runtime state when recomp::start
    // returns, so running static destructors/atexit handlers underneath
    // them can crash on quit -- exit directly instead (same approach as
    // other N64Recomp projects' main()).
    fflush(stdout);
    fflush(stderr);
    std::_Exit(EXIT_SUCCESS);
}
