// Entry point that wires this project's recompiled game code up to
// N64ModernRuntime (ultramodern + librecomp) and RecompFrontend
// (recompui + recompinput). Structurally modeled on
// bdragoncore/battle-tanx-recomp's src/main/main.cpp (same toolchain, same
// runtime, same recompui/librecomp APIs) -- nothing here is BattleTanx's
// own game logic or symbol addresses, just the generic plumbing every
// N64Recomp-based project using this runtime needs.
//
// What's still a placeholder, and why (see PROGRESS.md/STATUS.md for the
// underlying reverse-engineering status):
//   - `get_rsp_microcode` returns nullptr for every task. RT64 has its own
//     generic F3DEX-family GBI walker (see lib/rt64/src/gbi/*.cpp) that
//     handles GFX tasks via HLE without needing this game's own recompiled
//     microcode, so graphics may work without it. Audio tasks are not so
//     lucky -- this ROM's RSP audio microcode hasn't been identified yet
//     (PROGRESS.md item 6), so the game will hit `quit_exit` the first time
//     it submits an M_AUDTASK, printing which task type was unhandled.
//   - `GameEntry::save_type` is `AllowAll` (accepts EEPROM/SRAM/FlashRAM)
//     rather than this ROM's real save type, which hasn't been determined.
//   - UI assets (primary font, icons, promptfont) are modeled on
//     BanjoRecomp's, not designed for this game -- see STATUS.md round 86.
//   - Audio playback uses a plain SDL_QueueAudio push -- no resampling or
//     jitter smoothing. Good enough to hear whether audio works at all,
//     not tuned for it to sound clean.
//   - No mod/texture-pack content types, no launcher menu customization
//     (the library's own default_launcher_init_callback runs instead), no
//     patches/overlays registration -- there's nothing to register yet
//     (PROGRESS.md item 8).

#include <cstdio>
#include <cstdlib>
#include <cinttypes>
#include <atomic>
#include <mutex>
#include <vector>
#include <filesystem>
#include <exception>

#include "nfd.h"

#include "ultramodern/ultra64.h"
#include "ultramodern/ultramodern.hpp"

#define SDL_MAIN_HANDLED
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include "SDL.h"
#include "SDL_syswm.h"
#else
#include "SDL2/SDL.h"
#endif

#include "recompui/recompui.h"
#include "recompui/program_config.h"
#include "recompui/renderer.h"
#include "recompui/config.h"
#include "util/file.h"

#include "recompinput/input_state.h"
#include "recompinput/input_events.h"
#include "recompinput/profiles.h"
#include "recompinput/players.h"

#include "librecomp/game.hpp"
#include "librecomp/helpers.hpp"

// Generated into RecompiledFuncs/funcs.h by N64Recomp from this project's
// own battletanxga.us.rev0.toml (renamed from func_80071000 -- see
// [input] entrypoint in that file).
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// register_overlays.cpp -- wires N64Recomp's generated function-address
// lookup table into librecomp's runtime overlay system. Without this,
// indirect calls (function pointers/jump tables) fail with "Failed to find
// function at 0x..." -- see that file's own comment for the full story.
void register_btga_overlays();

static const std::string program_name = "BattleTanx: Global Assault Recompiled";
static const std::u8string program_id = u8"btgarecomp";
static const std::string version_string = "0.1.0";

template <typename... Ts>
[[noreturn]] static void exit_error(const char* fmt, Ts... args) {
    char buf[1024];
    std::snprintf(buf, sizeof(buf), fmt, args...);
    fprintf(stderr, "%s\n", buf);
    ultramodern::error_handling::message_box(buf);
    ultramodern::error_handling::quick_exit(__FILE__, __LINE__, __FUNCTION__);
}

// --- RSP microcode dispatch -------------------------------------------
// See the file-level comment: neither this ROM's GFX nor audio RSP
// microcode has been identified/recompiled yet. Returning nullptr here is
// the documented "not implemented" signal (recomp::rsp::callbacks_t::
// get_rsp_microcode_t's doc comment) -- ultramodern prints the task type
// to stderr and exits rather than running with garbage microcode.
#ifdef BTGA_HAS_RSP_AUDIO
// rsp/n_aspMain.cpp, generated by RSPRecomp from n_aspMain.us.rev0.toml
// (STATUS.md round 90). Graphics tasks are handled by RT64's own HLE.
RspExitReason n_aspMain(uint8_t* rdram, uint32_t ucode_addr);
#endif

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    switch (task->t.type) {
#ifdef BTGA_HAS_RSP_AUDIO
    case M_AUDTASK:
        return n_aspMain;
#endif
    default:
        fprintf(stderr, "No RSP microcode registered for task type %" PRIu32 ".\n", task->t.type);
        return nullptr;
    }
}

// --- Graphics / windowing -----------------------------------------------

// recompui's own code (ui_state.cpp) declares this as `extern SDL_Window*
// window;` and reads it directly -- not `static`, needs external linkage.
SDL_Window* window = nullptr;

static void checkpoint(const char* name) {
    fprintf(stdout, "checkpoint: %s\n", name);
    fflush(stdout);
}

static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    checkpoint("create_gfx: entered");

    SDL_SetHint(SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH, "1");
    SDL_SetHint(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, "1");

    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC) != 0) {
        exit_error("Failed to initialize SDL2: %s", SDL_GetError());
    }
    checkpoint("create_gfx: after SDL_Init");

    fprintf(stdout, "SDL Video Driver: %s\n", SDL_GetCurrentVideoDriver());
    fflush(stdout);

    return {};
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    checkpoint("create_window: entered");

    uint32_t flags = SDL_WINDOW_RESIZABLE;
#if defined(__APPLE__)
    flags |= SDL_WINDOW_METAL;
#elif defined(RT64_SDL_WINDOW_VULKAN)
    // Only defined on Linux (see CMakeLists.txt) -- Windows uses plume's
    // D3D12 backend instead, which doesn't need an SDL window flag (it
    // talks to the GPU through the raw HWND returned below), same as
    // bdragoncore/battle-tanx-recomp's own create_window.
    flags |= SDL_WINDOW_VULKAN;
#endif

    window = SDL_CreateWindow(program_name.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1280, 720, flags);
    if (window == nullptr) {
        exit_error("Failed to create window: %s", SDL_GetError());
    }
    checkpoint("create_window: after SDL_CreateWindow");

#if defined(_WIN32)
    SDL_SysWMinfo wm_info;
    SDL_VERSION(&wm_info.version);
    if (!SDL_GetWindowWMInfo(window, &wm_info)) {
        exit_error("Failed to get window info: %s", SDL_GetError());
    }
    checkpoint("create_window: after SDL_GetWindowWMInfo, returning");
    return ultramodern::renderer::WindowHandle{ wm_info.info.win.window, GetCurrentThreadId() };
#elif defined(__linux__) || defined(__ANDROID__)
    checkpoint("create_window: returning (non-Windows)");
    return ultramodern::renderer::WindowHandle{ window };
#else
    static_assert(false && "Only Linux and Windows are set up in this file so far -- see PROGRESS.md.");
#endif
}

static void update_gfx(void*) {
    static std::atomic<bool> first_call{true};
    if (first_call.exchange(false)) {
        checkpoint("update_gfx: first call");
    }
    // poll_inputs() only reads already-buffered SDL state (SDL_GetKeyboardState,
    // etc.) -- it never calls SDL_PollEvent, so it never pumps the window's
    // message queue. That's handle_events()'s job (see recompinput's
    // input_events.cpp): without calling it here, the window's message loop
    // is never serviced, and Windows marks it "Not Responding" even though
    // nothing has actually crashed or deadlocked. poll_inputs() is already
    // correctly wired as the ultramodern input_callbacks_t::poll_input
    // callback and doesn't need to run again from here too (matches
    // BanjoRecomp's own update_gfx, which calls only handle_events()).
    recompinput::handle_events();
}

// --- Audio ----------------------------------------------------------------
// Plain push-based playback: queue whatever the game hands us, report how
// much is still queued. No resampling/smoothing -- see file-level comment.

static SDL_AudioDeviceID audio_device = 0;
static std::mutex audio_mutex;
static uint32_t audio_channels = 2;
static uint32_t audio_frequency = 44100;

static bool open_audio_device(uint32_t frequency) {
    std::lock_guard<std::mutex> lock(audio_mutex);

    if (audio_device != 0) {
        SDL_CloseAudioDevice(audio_device);
        audio_device = 0;
    }

    SDL_AudioSpec desired{};
    desired.freq = static_cast<int>(frequency);
    desired.format = AUDIO_S16SYS;
    desired.channels = static_cast<Uint8>(audio_channels);
    desired.samples = 1024;

    SDL_AudioSpec obtained{};
    audio_device = SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);
    if (audio_device == 0) {
        fprintf(stderr, "Failed to open audio device: %s (continuing without sound)\n", SDL_GetError());
        return false;
    }

    audio_frequency = static_cast<uint32_t>(obtained.freq);
    SDL_PauseAudioDevice(audio_device, 0);
    return true;
}

static void queue_samples(int16_t* audio_data, size_t sample_count) {
    if (audio_device == 0) {
        return;
    }
    std::lock_guard<std::mutex> lock(audio_mutex);
    SDL_QueueAudio(audio_device, audio_data, static_cast<Uint32>(sample_count * sizeof(int16_t)));
}

static size_t get_frames_remaining() {
    if (audio_device == 0) {
        return 0;
    }
    std::lock_guard<std::mutex> lock(audio_mutex);
    Uint32 queued_bytes = SDL_GetQueuedAudioSize(audio_device);
    return queued_bytes / (audio_channels * sizeof(int16_t));
}

static void set_frequency(uint32_t frequency) {
    if (frequency != audio_frequency) {
        open_audio_device(frequency);
    }
}

// --- Input ------------------------------------------------------------

static ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    if (controller_num == 0) {
        return ultramodern::input::connected_device_info_t{
            .connected_device = ultramodern::input::Device::Controller,
            .connected_pak = ultramodern::input::Pak::None,
        };
    }
    return ultramodern::input::connected_device_info_t{
        .connected_device = ultramodern::input::Device::None,
        .connected_pak = ultramodern::input::Pak::None,
    };
}

// --- Misc callbacks -----------------------------------------------------

static std::string get_game_thread_name(const OSThread* t) {
    return "Game " + std::to_string(t->id);
}

// --- Game registration --------------------------------------------------
// recompui's own default launcher menu (ui_launcher.cpp) reads this exact
// global by name -- it must exist with this type for the link to succeed.
std::vector<recomp::GameEntry> supported_games = {
    {
        // XXH3_64 of the normalized big-endian .z64 (tools/normalize_rom.py),
        // computed against the ROM this project has been developed against
        // (see syms/rom_info.md) -- NOT the N64 header CRC1/CRC2.
        .rom_hash = 0x9c7467e763553529ULL,
        .internal_name = "BattleTanxGA",
        .display_name = "BattleTanx: Global Assault",
        .game_id = u8"btga.n64.us.1.0",
        .mod_game_id = "btga",
        // Not yet determined which save type this ROM actually uses --
        // AllowAll accepts EEPROM/SRAM/FlashRAM rather than guessing wrong.
        .save_type = recomp::SaveType::AllowAll,
        .thumbnail_bytes = {},
        .is_enabled = true,
        .decompression_routine = nullptr,
        .has_compressed_code = false,
        // entrypoint_address is a gpr (uint64_t). A plain 0x80071000 literal
        // zero-extends to 0x0000000080071000 -- but the MEM_B/MEM_W/MEM_H
        // macros (N64Recomp/include/recomp.h) subtract the *sign-extended*
        // KSEG0 base (0xFFFFFFFF80000000, matching real MIPS64 register
        // semantics: a 32-bit value in a 64-bit register is always sign-
        // extended), so a zero-extended address computes a ~4GB-off offset
        // into rdram instead of the intended small one, segfaulting on the
        // very first RDRAM write in do_rom_read(). Cast through int32_t
        // first to sign-extend, matching what N64Recomp's own generated
        // get_entrypoint_address() (RecompiledFuncs/lookup.cpp) does for
        // exactly this reason.
        .entrypoint_address = (gpr)(int32_t)0x80071000u,
        .entrypoint = recomp_entrypoint,
        .on_init_callback = nullptr,
    },
};

// std::terminate (any uncaught C++ exception, on any thread -- recomp::start
// spawns several) leads straight into ucrtbase's fail-fast abort path, which
// tears the process down without running atexit handlers or flushing stdio
// buffers. That's why redirected runs (`... > run_output.txt 2>&1`) have
// been showing up empty even when something threw and printed nothing --
// this handler force-flushes and prints the exception's own message first
// so it actually survives redirection.
[[noreturn]] static void report_unhandled_exception_and_abort() {
    if (std::exception_ptr eptr = std::current_exception()) {
        try {
            std::rethrow_exception(eptr);
        } catch (const std::exception& e) {
            fprintf(stderr, "UNHANDLED EXCEPTION: %s\n", e.what());
        } catch (...) {
            fprintf(stderr, "UNHANDLED EXCEPTION: (unrecognized exception type)\n");
        }
    } else {
        fprintf(stderr, "std::terminate() called with no active exception.\n");
    }
    fflush(stdout);
    fflush(stderr);
    std::abort();
}

int main(int argc, char** argv) {
    std::set_terminate(report_unhandled_exception_and_abort);
    fprintf(stdout, "main() started\n");
    fflush(stdout);

    recomp::Version project_version{};
    if (!recomp::Version::from_string(version_string, project_version)) {
        fprintf(stderr, "Invalid version string: %s\n", version_string.c_str());
        return EXIT_FAILURE;
    }

#define BTGA_CHECKPOINT(name) do { fprintf(stdout, "checkpoint: %s\n", name); fflush(stdout); } while (0)

    register_btga_overlays();
    BTGA_CHECKPOINT("after register_btga_overlays");

    BTGA_CHECKPOINT("before NFD_Init");
    NFD_Init();
    BTGA_CHECKPOINT("after NFD_Init");

    recompui::programconfig::set_program_name(program_name);
    recompui::programconfig::set_program_id(program_id);
    BTGA_CHECKPOINT("after set_program_name/id");

    SDL_InitSubSystem(SDL_INIT_AUDIO);
    BTGA_CHECKPOINT("after SDL_InitSubSystem(AUDIO)");
    if (!open_audio_device(audio_frequency)) {
        fprintf(stderr, "Continuing without sound.\n");
    }
    BTGA_CHECKPOINT("after open_audio_device");

    // Inter Variable (SIL OFL 1.1, assets/INTER_LICENSE.txt), the same primary
    // font BanjoRecomp registers with this same RecompFrontend. The family
    // name must match the one stored inside the font file: recompui's
    // generated base stylesheet sets `font-family` to it, and RmlUi draws no
    // text for a family it never loaded (STATUS.md round 86 -- the old
    // "Lato" didn't match LatoLatin-Regular.ttf's internal "LatoLatin").
    recompui::register_primary_font("InterVariable.ttf", "Inter Variable");
    BTGA_CHECKPOINT("after register_primary_font");

    recomp::register_config_path(recompui::file::get_app_folder_path());
    BTGA_CHECKPOINT("after register_config_path");

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }
    BTGA_CHECKPOINT("after register_game loop");

    recompinput::players::set_single_player_mode(true);
    BTGA_CHECKPOINT("after set_single_player_mode");

    // recompui::config::init_modal() (called from UIState::create_menus(),
    // itself called from inside RT64::Application::setup() on the gfx
    // thread) hard-requires recompui::config::finalize() to have already
    // run -- without it, "loaded_configs" stays false and/or the config
    // system is left in a state RT64/recompui doesn't expect, which was
    // crashing startup entirely (see STATUS.md). Every other N64Recomp
    // project using this same RecompFrontend runtime (e.g. BanjoRecomp's
    // banjo::init_config(), src/game/config.cpp) creates its config tabs
    // and calls finalize() before recomp::start() for exactly this reason.
    // No game-specific options exist yet (PROGRESS.md item 8), so this
    // registers only the library's own prefab tabs with default options.
    recompui::config::GeneralTabOptions general_tab_options{};
    recompui::config::create_general_tab(general_tab_options);
    recompui::config::create_graphics_tab();
    recompui::config::create_controls_tab();
    recompui::config::create_sound_tab();
    recompui::config::create_mods_tab();
    recompui::config::finalize();
    BTGA_CHECKPOINT("after config tabs + finalize");

    recomp::rsp::callbacks_t rsp_callbacks{
        .get_rsp_microcode = get_rsp_microcode,
    };

    ultramodern::renderer::callbacks_t renderer_callbacks{
        .create_render_context = [](uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
            checkpoint("create_render_context: entered");
            auto presentation_mode = ultramodern::renderer::PresentationMode::PresentEarly;
            auto ctx = recompui::renderer::create_render_context(rdram, window_handle, presentation_mode, developer_mode);
            checkpoint("create_render_context: returning");
            return ctx;
        },
    };

    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = create_gfx,
        .create_window = create_window,
        .update_gfx = update_gfx,
    };

    ultramodern::audio_callbacks_t audio_callbacks{
        .queue_samples = queue_samples,
        .get_frames_remaining = get_frames_remaining,
        .set_frequency = set_frequency,
    };

    ultramodern::input::callbacks_t input_callbacks{
        .poll_input = recompinput::poll_inputs,
        .get_input = recompinput::profiles::get_n64_input,
        .set_rumble = recompinput::set_rumble,
        .get_connected_device_info = get_connected_device_info,
    };

    ultramodern::events::callbacks_t events_callbacks{
        .vi_callback = recompinput::update_rumble,
        .gfx_init_callback = nullptr,
    };

    ultramodern::error_handling::callbacks_t error_handling_callbacks{
        .message_box = recompui::message_box,
    };

    ultramodern::threads::callbacks_t threads_callbacks{
        .get_game_thread_name = get_game_thread_name,
    };

    // recompui's own default launcher menu is used -- no
    // register_launcher_init_callback call here (see file-level comment).

    BTGA_CHECKPOINT("before recomp::start");
    recomp::start({
        .argc = argc,
        .argv = argv,
        .project_version = project_version,
        .rsp_callbacks = rsp_callbacks,
        .renderer_callbacks = renderer_callbacks,
        .audio_callbacks = audio_callbacks,
        .input_callbacks = input_callbacks,
        .gfx_callbacks = gfx_callbacks,
        .events_callbacks = events_callbacks,
        .error_handling_callbacks = error_handling_callbacks,
        .threads_callbacks = threads_callbacks,
    });

    NFD_Quit();

    // The game's threads are never joined by the runtime and may still be
    // blocked on (or spinning over) runtime state when recomp::start
    // returns, so running static destructors/atexit handlers underneath
    // them can crash on quit -- exit directly instead (same approach as
    // other N64Recomp projects' main()).
    fflush(stdout);
    fflush(stderr);
    std::_Exit(EXIT_SUCCESS);
}
