// Wires up N64Recomp's generated function-address lookup table
// (RecompiledFuncs/recomp_overlays.inl, regenerated by N64RecompCLI on every
// `N64Recomp battletanxga.us.rev0.toml` run) to librecomp's runtime overlay
// system. Without this call, recomp::overlays::register_overlays() is never
// invoked, so its internal func_map stays permanently empty -- most N64
// calls still work fine because N64Recomp resolves direct `jal` calls into
// direct C function calls at recompile time, but any genuinely *indirect*
// call (a function pointer or jump table entry) has to fall back to
// get_function()'s runtime func_map lookup, which fails with "Failed to
// find function at 0x..." (librecomp/src/overlays.cpp) for every such call
// with this piece missing.
#ifdef BTGA_HAS_RECOMPILED_FUNCS

#include "librecomp/overlays.hpp"

#include "../../RecompiledFuncs/recomp_overlays.inl"

void btga_install_crash_handler(const SectionTableEntry* sections, size_t num_sections);

void register_btga_overlays() {
    recomp::overlays::overlay_section_table_data_t sections{
        .code_sections = section_table,
        .num_code_sections = ARRLEN(section_table),
        .total_num_sections = num_sections,
    };

    recomp::overlays::overlays_by_index_t overlays{
        .table = overlay_sections_by_index,
        .len = ARRLEN(overlay_sections_by_index),
    };

    recomp::overlays::register_overlays(sections, overlays);

    // Crash reports name the faulting game function (src/main/crash_handler.cpp).
    btga_install_crash_handler(section_table, ARRLEN(section_table));
}

#else

// No RecompiledFuncs/recomp_overlays.inl yet (fresh clone, ROM not in place
// / N64Recomp not run yet -- see CMakeLists.txt). Nothing to register.
void register_btga_overlays() {}

#endif
